name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: terraform
          workspace: STRWIKER
          variables: |
            vercel_api_token = "${{secrets.VERCEL_TERRAFORM_API_TOKEN}}"
            github_owner = "${{github.repository_owner}}"
            github_repository_name = "${{github.event.repository.name}}"
            github_access_token = "${{secrets.RW_GH_SECRETS_GH_TOKEN}}"
            supabase_access_token = "${{secrets.SUPABASE_ACCESS_TOKEN}}"
            supabase_organization_id = "${{secrets.SUPABASE_ORGANIZATION_ID}}"
            supabase_database_password = "${{secrets.SUPABASE_DATABASE_PASSWORD}}"