name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Apply Terraform
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform plan
        if: github.event_name == 'workflow_dispatch'
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          variables: |
            vercel_api_token = "${{secrets.VERCEL_TERRAFORM_API_TOKEN}}"
            github_repository_name = "${{github.event.repository.name}}"
            supabase_access_token = "${{secrets.SUPABASE_ACCESS_TOKEN}}"
            supabase_organization_id = "${{secrets.SUPABASE_ORGANIZATION_ID}}"
            supabase_database_password = "${{secrets.SUPABASE_DATABASE_PASSWORD}}"

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          variables: |
            vercel_api_token = "${{secrets.VERCEL_TERRAFORM_API_TOKEN}}"
            github_repository_name = "${{github.event.repository.name}}"
            supabase_access_token = "${{secrets.SUPABASE_ACCESS_TOKEN}}"
            supabase_organization_id = "${{secrets.SUPABASE_ORGANIZATION_ID}}"
            supabase_database_password = "${{secrets.SUPABASE_DATABASE_PASSWORD}}"
          # only auto approve for manual runs
          auto_approve: ${{ github.event_name  == 'workflow_dispatch' }}